const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Nairobi,Kenya."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "254797633626";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "recording" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "254797992027,254xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_14_10_07_20_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICAxODEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjE4LFxuICAgICAgICAzMCxcbiAgICAgICAgMTQwLFxuICAgICAgICA5NixcbiAgICAgICAgMzMsXG4gICAgICAgIDg5LFxuICAgICAgICAyNDcsXG4gICAgICAgIDE3LFxuICAgICAgICA0MixcbiAgICAgICAgOTQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTgyLFxuICAgICAgICA3NSxcbiAgICAgICAgMjgsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyMTAsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTU1LFxuICAgICAgICA2MyxcbiAgICAgICAgMTgzLFxuICAgICAgICAxMTAsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTEyLFxuICAgICAgICAxNSxcbiAgICAgICAgMTk2LFxuICAgICAgICA5NSxcbiAgICAgICAgMTAwLFxuICAgICAgICA4NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3NixcbiAgICAgICAgMTcyLFxuICAgICAgICAxODgsXG4gICAgICAgIDE3LFxuICAgICAgICAyMTksXG4gICAgICAgIDc3LFxuICAgICAgICAyNDYsXG4gICAgICAgIDIwMSxcbiAgICAgICAgNyxcbiAgICAgICAgNDEsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMTcsXG4gICAgICAgIDQyLFxuICAgICAgICA1NixcbiAgICAgICAgNjYsXG4gICAgICAgIDEzMSxcbiAgICAgICAgNSxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNzksXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjM2LFxuICAgICAgICA3NixcbiAgICAgICAgOSxcbiAgICAgICAgODAsXG4gICAgICAgIDQwLFxuICAgICAgICAxNSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNDgsXG4gICAgICAgIDgyLFxuICAgICAgICAxMzEsXG4gICAgICAgIDU4XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjgsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTE5LFxuICAgICAgICAzMCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxMzgsXG4gICAgICAgIDQ3LFxuICAgICAgICA0MCxcbiAgICAgICAgODcsXG4gICAgICAgIDE2MixcbiAgICAgICAgNDUsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTk2LFxuICAgICAgICA0MSxcbiAgICAgICAgMjAsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjA1LFxuICAgICAgICAxOTIsXG4gICAgICAgIDAsXG4gICAgICAgIDg1LFxuICAgICAgICAyMzAsXG4gICAgICAgIDEwMSxcbiAgICAgICAgNSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxNjMsXG4gICAgICAgIDc0LFxuICAgICAgICA4NixcbiAgICAgICAgMzAsXG4gICAgICAgIDU3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDEwOCxcbiAgICAgICAgNjlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc5LFxuICAgICAgICAxNjIsXG4gICAgICAgIDI4LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIzLFxuICAgICAgICAyNixcbiAgICAgICAgNTEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgNTQsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNjUsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTkwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE0MyxcbiAgICAgICAgOTIsXG4gICAgICAgIDE5NCxcbiAgICAgICAgNzcsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNTEsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMzIsXG4gICAgICAgIDU4LFxuICAgICAgICAzOSxcbiAgICAgICAgMjUyLFxuICAgICAgICAxNDUsXG4gICAgICAgIDE0NCxcbiAgICAgICAgNjIsXG4gICAgICAgIDk5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDAsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTY4LFxuICAgICAgICA2MixcbiAgICAgICAgMzQsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTQ3LFxuICAgICAgICA3NyxcbiAgICAgICAgMTI5LFxuICAgICAgICAyNCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNTAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTkxLFxuICAgICAgICAxNzIsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNTUsXG4gICAgICAgIDU0LFxuICAgICAgICAyMTUsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTk0LFxuICAgICAgICAyMzksXG4gICAgICAgIDg5LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE5OCxcbiAgICAgICAgNzMsXG4gICAgICAgIDk4LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTIzLFxuICAgICAgICA4M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5MyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjcsXG4gICAgICAgIDIzMCxcbiAgICAgICAgODgsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTAyLFxuICAgICAgICA4LFxuICAgICAgICA3NCxcbiAgICAgICAgNTksXG4gICAgICAgIDE4NixcbiAgICAgICAgMTEwLFxuICAgICAgICAxODEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjAzLFxuICAgICAgICA2OSxcbiAgICAgICAgMTYyLFxuICAgICAgICAxOSxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNzAsXG4gICAgICAgIDYzLFxuICAgICAgICAyMjksXG4gICAgICAgIDI1MyxcbiAgICAgICAgNjksXG4gICAgICAgIDE5NyxcbiAgICAgICAgNixcbiAgICAgICAgMTk5LFxuICAgICAgICAxMSxcbiAgICAgICAgMTM0LFxuICAgICAgICAxMjNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyOSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxMTJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICA5MyxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAxMThcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3OSxcbiAgICAgICAgMTQ5LFxuICAgICAgICA2MCxcbiAgICAgICAgMyxcbiAgICAgICAgMjIzLFxuICAgICAgICAxNDYsXG4gICAgICAgIDIwNCxcbiAgICAgICAgODksXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMjUsXG4gICAgICAgIDQ5LFxuICAgICAgICAyMyxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDQxLFxuICAgICAgICAxNjUsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyMCxcbiAgICAgICAgMTg3LFxuICAgICAgICA3OSxcbiAgICAgICAgMTAxLFxuICAgICAgICA4NCxcbiAgICAgICAgNjcsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMixcbiAgICAgICAgOTQsXG4gICAgICAgIDg5LFxuICAgICAgICAxNDksXG4gICAgICAgIDEzNCxcbiAgICAgICAgNDgsXG4gICAgICAgIDEzNixcbiAgICAgICAgNTcsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTksXG4gICAgICAgIDE2MixcbiAgICAgICAgMjAzLFxuICAgICAgICAxMjcsXG4gICAgICAgIDYyLFxuICAgICAgICAxMTYsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjE4LFxuICAgICAgICAxNyxcbiAgICAgICAgMzQsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjUwLFxuICAgICAgICAyNDYsXG4gICAgICAgIDQ1LFxuICAgICAgICAyLFxuICAgICAgICAyMyxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMjksXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjQxLFxuICAgICAgICAyNyxcbiAgICAgICAgMTYzLFxuICAgICAgICAyMSxcbiAgICAgICAgNDksXG4gICAgICAgIDEyOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTQ3LFxuICBcImFkdlNlY3JldEtleVwiOiBcIjhPZTNJMkY0WlVrNmM2TTJYSWR5Q0tnNUtZak5XY2JSZWN4M0tJaGcvNE09XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0Nzk3NjMzNjI2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIxMUI2RjYxNjNGRTYzRTRFRjU5OEI5MjBFQ0EwMDFDMlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjE0ODQ1OTdcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwib2hKSGNsM2FRMEdBLXExeV9DNmliZ1wiLFxuICBcInBob25lSWRcIjogXCJkOGNhN2Y2MS1iZTYwLTRmYzQtYWYzMi01ZTljOWFlYjRjM2VcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjgsXG4gICAgICAyNDgsXG4gICAgICAyNTAsXG4gICAgICAyNDksXG4gICAgICAxMzcsXG4gICAgICAxNyxcbiAgICAgIDE2NSxcbiAgICAgIDQyLFxuICAgICAgMTYyLFxuICAgICAgMjQwLFxuICAgICAgMjI5LFxuICAgICAgNTYsXG4gICAgICAxMyxcbiAgICAgIDE5MSxcbiAgICAgIDE5MSxcbiAgICAgIDIwMSxcbiAgICAgIDEwNCxcbiAgICAgIDgsXG4gICAgICAxNDIsXG4gICAgICAxMzdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMzYsXG4gICAgICAzLFxuICAgICAgMTIsXG4gICAgICAxMDAsXG4gICAgICAxNjQsXG4gICAgICA3LFxuICAgICAgMTk5LFxuICAgICAgMTYyLFxuICAgICAgNDYsXG4gICAgICAxNjMsXG4gICAgICAyNDksXG4gICAgICA1NyxcbiAgICAgIDIwOSxcbiAgICAgIDEwMSxcbiAgICAgIDE2NyxcbiAgICAgIDE5MCxcbiAgICAgIDk1LFxuICAgICAgMTMyLFxuICAgICAgMjMxLFxuICAgICAgODdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiWUFLM1hSQVpcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1NDc5NzYzMzYyNjoxM0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIkRlUENNYXN0ZXJcIixcbiAgICBcImxpZFwiOiBcIjIwOTg4MjYxOTg0MjY3NzoxM0BsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNNMlBxWllHRUxDSzc3UUdHQUlnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIkpCeHVsZmhrYStNMzU5YzM4aFFQcFowSG1kd2F3RjFqZis4eExHd25FSGM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiR2o4bUVSWGpucUVYQW9tdVJMOHZhZlhDa2hjZS9rcnhiYmo4U3BrWGNtWHpaQlZkTnJwVlltWUtKZEc1RTlvVGROSk1wWFJISWk0YmZSaHk5VFB2Q1E9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiUElwaTJGY2g4NWNrNlZVU1Z3MGg2S21qZHRtSDBpMXZzSkNka3BGNm5kNjJJdXBsazVTWlMyWTU5SE1xRVFXWndSNHc4UC9PbU5YSXlwVEYrczduakE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU0Nzk3NjMzNjI2OjEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNDksXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDExOVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIxNDg0NTk0LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBR050XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFHTnQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJUYy9xVkRwVjNzSm1YZnl5dHZlTjJTNVp2cHYwVU5LaUdZbzJiWC9CeTIwPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE2NTc0MjM4MTUsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMTM0ODU1Mzk1M1wifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
